//in number output
console.log(true&true)
console.log(true&false)
console.log(false&true)
console.log(false&false)
console.log(true|true)
console.log(true|false)
console.log(false|true)
console.log(false|false)
console.log(false*4)
console.log(true*5)