//logical operator(come in true and fale)
console.log(true&&true)
console.log(true&&false)
console.log(false&&true)
console.log(false&&false)
console.log(true||true)
console.log(true||false)
console.log(false||true)
console.log(false||false)
